# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        ideaVersion: [ '2022.2', '2022.3', '2023.1', '2023.2', '2023.2.4' ]
        experimental: [ false ]
        include:
          - { ideaVersion: LATEST-EAP-SNAPSHOT, experimental: true }

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build Plugin
      uses: gradle/gradle-build-action@v2
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.ideaVersion }}
      with:
        arguments: buildPlugin

    - name: Verify Plugin
      uses: gradle/gradle-build-action@v2
      env:
          ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.ideaVersion }}
      with:
          arguments: verifyPlugin

  publish:
    needs: build
    environment: marketplace
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      env:
        MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
      with:
        arguments: publishPlugin
